In [1]:
from keras.preprocessing.text import one_hot #Libraries USed Tensorflow < 2.0  and keras

Using TensorFlow backend.
C:\Users\ABHIROCKZZZ\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\ABHIROCKZZZ\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\ABHIROCKZZZ\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\ABHIROCKZZZ\Anaconda3\lib\site-packages\tensorflow\py

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [9]:
#Vocabulary size
voc_size = 10000

One Hot representation

In [10]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[1178, 2358, 593, 7453], [1178, 2358, 593, 3632], [1178, 9912, 593, 4741], [3125, 9238, 4335, 7471, 2353], [3125, 9238, 4335, 7471, 8120], [5272, 1178, 4352, 593, 3032], [6912, 110, 2888, 7471]]


Word Embedding representation

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1178 2358  593 7453]
 [   0    0    0    0 1178 2358  593 3632]
 [   0    0    0    0 1178 9912  593 4741]
 [   0    0    0 3125 9238 4335 7471 2353]
 [   0    0    0 3125 9238 4335 7471 8120]
 [   0    0    0 5272 1178 4352  593 3032]
 [   0    0    0    0 6912  110 2888 7471]]


In [14]:
dim = 10

In [15]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam', 'mse')

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [16]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(embedded_docs))

[[[ 0.03087754 -0.00205876 -0.01424019  0.03873278 -0.03793333
    0.02762209 -0.04747114 -0.0142618  -0.02037637 -0.01250435]
  [ 0.03087754 -0.00205876 -0.01424019  0.03873278 -0.03793333
    0.02762209 -0.04747114 -0.0142618  -0.02037637 -0.01250435]
  [ 0.03087754 -0.00205876 -0.01424019  0.03873278 -0.03793333
    0.02762209 -0.04747114 -0.0142618  -0.02037637 -0.01250435]
  [ 0.03087754 -0.00205876 -0.01424019  0.03873278 -0.03793333
    0.02762209 -0.04747114 -0.0142618  -0.02037637 -0.01250435]
  [-0.01911779 -0.0383072  -0.00389413 -0.01446541 -0.04751326
   -0.00177318 -0.04228026 -0.01643775 -0.04914431  0.01773058]
  [ 0.00560383 -0.0333329  -0.02994945 -0.01212927 -0.01613928
   -0.00742276  0.01041162 -0.00853261  0.03215294  0.02799397]
  [-0.03487601 -0.01983945  0.00944209 -0.03506226 -0.01139458
   -0.00969286 -0.04997209  0.04700876  0.03968665  0.03889736]
  [-0.00616574  0.02963213  0.00223821 -0.04920459  0.0356213
   -0.0213079  -0.02901399  0.0261763  -0.0082218

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 1178, 2358,  593, 7453])

In [19]:
print(model.predict(embedded_docs)[0])

[[ 0.03087754 -0.00205876 -0.01424019  0.03873278 -0.03793333  0.02762209
  -0.04747114 -0.0142618  -0.02037637 -0.01250435]
 [ 0.03087754 -0.00205876 -0.01424019  0.03873278 -0.03793333  0.02762209
  -0.04747114 -0.0142618  -0.02037637 -0.01250435]
 [ 0.03087754 -0.00205876 -0.01424019  0.03873278 -0.03793333  0.02762209
  -0.04747114 -0.0142618  -0.02037637 -0.01250435]
 [ 0.03087754 -0.00205876 -0.01424019  0.03873278 -0.03793333  0.02762209
  -0.04747114 -0.0142618  -0.02037637 -0.01250435]
 [-0.01911779 -0.0383072  -0.00389413 -0.01446541 -0.04751326 -0.00177318
  -0.04228026 -0.01643775 -0.04914431  0.01773058]
 [ 0.00560383 -0.0333329  -0.02994945 -0.01212927 -0.01613928 -0.00742276
   0.01041162 -0.00853261  0.03215294  0.02799397]
 [-0.03487601 -0.01983945  0.00944209 -0.03506226 -0.01139458 -0.00969286
  -0.04997209  0.04700876  0.03968665  0.03889736]
 [-0.00616574  0.02963213  0.00223821 -0.04920459  0.0356213  -0.0213079
  -0.02901399  0.0261763  -0.00822186  0.01891856]]
